In [2]:
# Import dependencies
import pandas as pd
import numpy as np
pd.set_option('max_colwidth', 400)

In [4]:
# Read the data into a Pandas DataFrame
crowdfunding = pd.read_excel('Resources/crowdfunding.xlsx')
crowdfunding.head()

,cf_id,contact_id,company_name,blurb,goal,pledged,outcome,backers_count,country,currency,launched_at,deadline,staff_pick,spotlight,category & sub-category
0,147,4661,"Baldwin, Riley and Jackson",Pre-emptive tertiary standardization,100,0,failed,0,CA,CAD,1581573600,1614578400,False,False,food/food trucks
1,1621,3765,Odom Inc,Managed bottom-line architecture,1400,14560,successful,158,US,USD,1611554400,1621918800,False,True,music/rock
2,1812,4187,"Melton, Robinson and Fritz",Function-based leadingedge pricing structure,108400,142523,successful,1425,AU,AUD,1608184800,1640844000,False,False,technology/web
3,2156,4941,"Mcdonald, Gonzalez and Ross",Vision-oriented fresh-thinking conglomeration,4200,2477,failed,24,US,USD,1634792400,1642399200,False,False,music/rock
4,1365,2199,Larson-Little,Proactive foreground core,7600,5265,failed,53,US,USD,1608530400,1629694800,False,False,theater/plays

In [27]:
# Get a brief summary of the crowdfunding_info DataFrame.
crowdfunding.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   cf_id                    1000 non-null   int64
 1   contact_id               1000 non-null   int64
 2   company_name             1000 non-null   object
 3   blurb                    1000 non-null   object
 4   goal                     1000 non-null   int64
 5   pledged                  1000 non-null   int64
 6   outcome                  1000 non-null   object
 7   backers_count            1000 non-null   int64
 8   country                  1000 non-null   object
 9   currency                 1000 non-null   object
 10  launched_at              1000 non-null   int64
 11  deadline                 1000 non-null   int64
 12  staff_pick               1000 non-null   bool
 13  spotlight                1000 non-null   bool
 14  category & sub-category  1000 non-null   object
dtypes: bool(2), int64(7), object(6)
memory usage: 103.6+ KB

In [28]:
# Get the crowdfunding_info_df columns.
crowdfunding.columns

Index(['cf_id', 'contact_id', 'company_name', 'blurb', 'goal', 'pledged',
       'outcome', 'backers_count', 'country', 'currency', 'launched_at',
       'deadline', 'staff_pick', 'spotlight', 'category & sub-category'],
      dtype='object')

In [35]:

# Assign the category and subcategory values to category and subcategory columns.
data={'category': ['categoryA','categoryB'],
      'subcategory': ['subcategoryA', 'subcategoryB']
      }
df=crowdfunding
print("Before assigning values:")
crowdfunding

Before assigning values:

,cf_id,contact_id,company_name,blurb,goal,pledged,outcome,backers_count,country,currency,launched_at,deadline,staff_pick,spotlight,category & sub-category
0,147,4661,"Baldwin, Riley and Jackson",Pre-emptive tertiary standardization,100,0,failed,0,CA,CAD,1581573600,1614578400,False,False,food/food trucks
1,1621,3765,Odom Inc,Managed bottom-line architecture,1400,14560,successful,158,US,USD,1611554400,1621918800,False,True,music/rock
2,1812,4187,"Melton, Robinson and Fritz",Function-based leadingedge pricing structure,108400,142523,successful,1425,AU,AUD,1608184800,1640844000,False,False,technology/web
3,2156,4941,"Mcdonald, Gonzalez and Ross",Vision-oriented fresh-thinking conglomeration,4200,2477,failed,24,US,USD,1634792400,1642399200,False,False,music/rock
4,1365,2199,Larson-Little,Proactive foreground core,7600,5265,failed,53,US,USD,1608530400,1629694800,False,False,theater/plays
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,2986,3684,Manning-Hamilton,Vision-oriented scalable definition,97300,153216,successful,2043,US,USD,1609221600,1622350800,False,True,food/food trucks
996,2031,5784,Butler LLC,Future-proofed upward-trending migration,6600,4814,failed,112,US,USD,1634274000,1638252000,False,False,theater/plays
997,1627,1498,Ball LLC,Right-sized full-range throughput,7600,4603,canceled,139,IT,EUR,1636174800,1639116000,False,False,theater/plays
998,2175,6073,"Taylor, Santiago and Flores",Polarized composite customer loyalty,66600,37823,failed,374,US,USD,1602133200,1618117200,False,True,music/indie rock
999,1788,4939,"Hernandez, Norton and Kelley",Expanded eco-centric policy,111100,62819,canceled,1122,US,USD,1609308000,1629262800,False,False,food/food trucks

In [37]:

# Split the 'Category & Sub-Category' column into 'Category' and 'Sub-Category' columns
crowdfunding[['category', 'sub-category']] = crowdfunding['category & sub-category'].str.split('/', n=1, expand=True)

# Display the updated DataFrame
print("After assigning values:")
crowdfunding

After assigning values:

,cf_id,contact_id,company_name,blurb,goal,pledged,outcome,backers_count,country,currency,launched_at,deadline,staff_pick,spotlight,category & sub-category,category,sub-category
0,147,4661,"Baldwin, Riley and Jackson",Pre-emptive tertiary standardization,100,0,failed,0,CA,CAD,1581573600,1614578400,False,False,food/food trucks,food,food trucks
1,1621,3765,Odom Inc,Managed bottom-line architecture,1400,14560,successful,158,US,USD,1611554400,1621918800,False,True,music/rock,music,rock
2,1812,4187,"Melton, Robinson and Fritz",Function-based leadingedge pricing structure,108400,142523,successful,1425,AU,AUD,1608184800,1640844000,False,False,technology/web,technology,web
3,2156,4941,"Mcdonald, Gonzalez and Ross",Vision-oriented fresh-thinking conglomeration,4200,2477,failed,24,US,USD,1634792400,1642399200,False,False,music/rock,music,rock
4,1365,2199,Larson-Little,Proactive foreground core,7600,5265,failed,53,US,USD,1608530400,1629694800,False,False,theater/plays,theater,plays
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,2986,3684,Manning-Hamilton,Vision-oriented scalable definition,97300,153216,successful,2043,US,USD,1609221600,1622350800,False,True,food/food trucks,food,food trucks
996,2031,5784,Butler LLC,Future-proofed upward-trending migration,6600,4814,failed,112,US,USD,1634274000,1638252000,False,False,theater/plays,theater,plays
997,1627,1498,Ball LLC,Right-sized full-range throughput,7600,4603,canceled,139,IT,EUR,1636174800,1639116000,False,False,theater/plays,theater,plays
998,2175,6073,"Taylor, Santiago and Flores",Polarized composite customer loyalty,66600,37823,failed,374,US,USD,1602133200,1618117200,False,True,music/indie rock,music,indie rock
999,1788,4939,"Hernandez, Norton and Kelley",Expanded eco-centric policy,111100,62819,canceled,1122,US,USD,1609308000,1629262800,False,False,food/food trucks,food,food trucks

In [68]:
categories = ["category"] 
unique_categories = list(set(unique_categories))

subcategories = ["subcategory"]
unique_subcategories = list(set(unique_subcategories))

print("Unique Categories:", category)
print("Unique Subcategories:", subcategories)

Unique Categories:     category_id    category
0          cat1        food
1          cat2       music
2          cat3  technology
3          cat2       music
4          cat4     theater
..          ...         ...
995        cat1        food
996        cat4     theater
997        cat4     theater
998        cat2       music
999        cat1        food

[1000 rows x 2 columns]
Unique Subcategories: ['subcategory']

In [69]:
unique_categories = list(set(categories))

unique_subcategories = list(set(subcategories))

print("Unique Categories:", unique_categories)
print("Unique Subcategories:", unique_subcategories)

Unique Categories: ['category']
Unique Subcategories: ['subcategory']

In [60]:
#Find the unique categories in the 'category' column:
unique_categories = crowdfunding['category'].unique()

#Create a new DataFrame to store the mapping of category names to category IDs:
category_mapping = pd.DataFrame({'category': unique_categories})

#Add a new column 'category_id' to the category_mapping DataFrame with entries going sequentially from "cat1" to "catn":
category_mapping['category_id'] = 'cat' + (category_mapping.index + 1).astype(str)

#Merge the original DataFrame crowdfunding_data with the category_mapping DataFrame to add the 'category_id' column based on the 'category' column:
crowdfunding = crowdfunding.merge(category_mapping, on='category', how='left')

crowdfunding

,cf_id,contact_id,company_name,blurb,goal,pledged,outcome,backers_count,country,currency,launched_at,deadline,staff_pick,spotlight,category & sub-category,category,sub-category,category_id_x,category_id_y
0,147,4661,"Baldwin, Riley and Jackson",Pre-emptive tertiary standardization,100,0,failed,0,CA,CAD,1581573600,1614578400,False,False,food/food trucks,food,food trucks,cat1,cat1
1,1621,3765,Odom Inc,Managed bottom-line architecture,1400,14560,successful,158,US,USD,1611554400,1621918800,False,True,music/rock,music,rock,cat2,cat2
2,1812,4187,"Melton, Robinson and Fritz",Function-based leadingedge pricing structure,108400,142523,successful,1425,AU,AUD,1608184800,1640844000,False,False,technology/web,technology,web,cat3,cat3
3,2156,4941,"Mcdonald, Gonzalez and Ross",Vision-oriented fresh-thinking conglomeration,4200,2477,failed,24,US,USD,1634792400,1642399200,False,False,music/rock,music,rock,cat2,cat2
4,1365,2199,Larson-Little,Proactive foreground core,7600,5265,failed,53,US,USD,1608530400,1629694800,False,False,theater/plays,theater,plays,cat4,cat4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,2986,3684,Manning-Hamilton,Vision-oriented scalable definition,97300,153216,successful,2043,US,USD,1609221600,1622350800,False,True,food/food trucks,food,food trucks,cat1,cat1
996,2031,5784,Butler LLC,Future-proofed upward-trending migration,6600,4814,failed,112,US,USD,1634274000,1638252000,False,False,theater/plays,theater,plays,cat4,cat4
997,1627,1498,Ball LLC,Right-sized full-range throughput,7600,4603,canceled,139,IT,EUR,1636174800,1639116000,False,False,theater/plays,theater,plays,cat4,cat4
998,2175,6073,"Taylor, Santiago and Flores",Polarized composite customer loyalty,66600,37823,failed,374,US,USD,1602133200,1618117200,False,True,music/indie rock,music,indie rock,cat2,cat2
999,1788,4939,"Hernandez, Norton and Kelley",Expanded eco-centric policy,111100,62819,canceled,1122,US,USD,1609308000,1629262800,False,False,food/food trucks,food,food trucks,cat1,cat1

In [43]:
# Specify the columns you want to extract and the desired order
selected_columns = ['category_id', 'category']

# Read the selected columns from the CSV file into a new DataFrame
category = pd.read_csv(r'C:\Users\soone\Crowdfunding_ETL\crowdfunding_data.csv', usecols=selected_columns)
category = category[['category_id', 'category']]

print(category)

    category_id    category
0          cat1        food
1          cat2       music
2          cat3  technology
3          cat2       music
4          cat4     theater
..          ...         ...
995        cat1        food
996        cat4     theater
997        cat4     theater
998        cat2       music
999        cat1        food

[1000 rows x 2 columns]

In [51]:
#Find the unique categories in the 'sub-category' column:
unique_subcategories = crowdfunding['sub-category'].unique()

#Create a new DataFrame to store the mapping of sub-category names to sub-category IDs:
subcategory_mapping = pd.DataFrame({'sub-category': unique_subcategories})

#Add a new column 'sub-category_id' to the sub-category_mapping DataFrame with entries going sequentially from "cat1" to "catn":
subcategory_mapping['sub-category_id'] = 'subcat' + (subcategory_mapping.index + 1).astype(str)

#Merge the original DataFrame crowdfunding_data with the category_mapping DataFrame to add the 'sub-category_id' column based on the 'sub-category' column:
subcategory_df = crowdfunding.merge(subcategory_mapping, on='sub-category', how='left')

subcategory_df

,cf_id,contact_id,company_name,blurb,goal,pledged,outcome,backers_count,country,currency,launched_at,deadline,staff_pick,spotlight,category & sub-category,category,sub-category,category_id,sub-category_id
0,147,4661,"Baldwin, Riley and Jackson",Pre-emptive tertiary standardization,100,0,failed,0,CA,CAD,1581573600,1614578400,False,False,food/food trucks,food,food trucks,cat1,subcat1
1,1621,3765,Odom Inc,Managed bottom-line architecture,1400,14560,successful,158,US,USD,1611554400,1621918800,False,True,music/rock,music,rock,cat2,subcat2
2,1812,4187,"Melton, Robinson and Fritz",Function-based leadingedge pricing structure,108400,142523,successful,1425,AU,AUD,1608184800,1640844000,False,False,technology/web,technology,web,cat3,subcat3
3,2156,4941,"Mcdonald, Gonzalez and Ross",Vision-oriented fresh-thinking conglomeration,4200,2477,failed,24,US,USD,1634792400,1642399200,False,False,music/rock,music,rock,cat2,subcat2
4,1365,2199,Larson-Little,Proactive foreground core,7600,5265,failed,53,US,USD,1608530400,1629694800,False,False,theater/plays,theater,plays,cat4,subcat4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,2986,3684,Manning-Hamilton,Vision-oriented scalable definition,97300,153216,successful,2043,US,USD,1609221600,1622350800,False,True,food/food trucks,food,food trucks,cat1,subcat1
996,2031,5784,Butler LLC,Future-proofed upward-trending migration,6600,4814,failed,112,US,USD,1634274000,1638252000,False,False,theater/plays,theater,plays,cat4,subcat4
997,1627,1498,Ball LLC,Right-sized full-range throughput,7600,4603,canceled,139,IT,EUR,1636174800,1639116000,False,False,theater/plays,theater,plays,cat4,subcat4
998,2175,6073,"Taylor, Santiago and Flores",Polarized composite customer loyalty,66600,37823,failed,374,US,USD,1602133200,1618117200,False,True,music/indie rock,music,indie rock,cat2,subcat8
999,1788,4939,"Hernandez, Norton and Kelley",Expanded eco-centric policy,111100,62819,canceled,1122,US,USD,1609308000,1629262800,False,False,food/food trucks,food,food trucks,cat1,subcat1

In [54]:
# Selecting only two columns from the 'subcategory' DataFrame
subcategory = subcategory[['sub-category_id', 'sub-category']]

# Display the new DataFrame

subcategory

    sub-category_id sub-category
0           subcat1  food trucks
1           subcat2         rock
2           subcat3          web
3           subcat2         rock
4           subcat4        plays
..              ...          ...
995         subcat1  food trucks
996         subcat4        plays
997         subcat4        plays
998         subcat8   indie rock
999         subcat1  food trucks

[1000 rows x 2 columns]

In [55]:
# Get the number of distinct values in the categories and subcategories lists.
print(len(crowdfunding))

1000

In [ ]:
# Create a category DataFrame with the category_id array as the category_id and categories list as the category name.

# Create a category DataFrame with the subcategory_id array as the subcategory_id and subcategories list as the subcategory name.

In [56]:
crowdfunding_data

NameError: name 'crowdfunding_data' is not defined

In [17]:
# Export categories_df and subcategories_df as CSV files.
crowdfunding_data.to_csv("Resources/category.csv", index=False)

In [25]:
# Create a copy of the crowdfunding_info_df DataFrame name campaign_df. 
crowdfunding_data = crowdfunding_data.copy()
crowdfunding_data.head()

,cf_id,contact_id,company_name,blurb,goal,pledged,outcome,backers_count,country,currency,launched_at,deadline,staff_pick,spotlight,category & sub-category,category,sub-category,category_id
0,147,4661,"Baldwin, Riley and Jackson",Pre-emptive tertiary standardization,100,0,failed,0,CA,CAD,1581573600,1614578400,False,False,food/food trucks,food,food trucks,cat1
1,1621,3765,Odom Inc,Managed bottom-line architecture,1400,14560,successful,158,US,USD,1611554400,1621918800,False,True,music/rock,music,rock,cat2
2,1812,4187,"Melton, Robinson and Fritz",Function-based leadingedge pricing structure,108400,142523,successful,1425,AU,AUD,1608184800,1640844000,False,False,technology/web,technology,web,cat3
3,2156,4941,"Mcdonald, Gonzalez and Ross",Vision-oriented fresh-thinking conglomeration,4200,2477,failed,24,US,USD,1634792400,1642399200,False,False,music/rock,music,rock,cat2
4,1365,2199,Larson-Little,Proactive foreground core,7600,5265,failed,53,US,USD,1608530400,1629694800,False,False,theater/plays,theater,plays,cat4

In [23]:
# Format the launched_date and end_date columns to datetime format
from datetime import datetime as dt

In [24]:
# Merge the campaign_df with the category_df on the "category" column and 
# the subcategory_df on the "subcategory" column.


crowdfunding_data
crowdfunding_data.tail(10)

,cf_id,contact_id,company_name,blurb,goal,pledged,outcome,backers_count,country,currency,launched_at,deadline,staff_pick,spotlight,category & sub-category,category,sub-category,category_id
990,1561,5500,Ortiz-Roberts,Devolved foreground customer loyalty,7800,6839,failed,64,US,USD,1623214800,1623992400,False,True,film & video/drama,film & video,drama,cat5
991,2632,3494,Ramirez LLC,Reduced reciprocal focus group,9800,11091,successful,241,US,USD,1607493600,1622005200,False,True,music/rock,music,rock,cat2
992,439,3924,Morrow Inc,Networked global migration,3100,13223,successful,132,US,USD,1592110800,1612850400,False,True,film & video/drama,film & video,drama,cat5
993,461,3521,Erickson-Rogers,De-engineered even-keeled definition,9800,7608,canceled,75,IT,EUR,1625288400,1625720400,False,True,photography/photography books,photography,photography books,cat8
994,1419,5262,"Leach, Rich and Price",Implemented bi-directional flexibility,141100,74073,failed,842,US,USD,1636956000,1638856800,False,True,publishing/translations,publishing,translations,cat6
995,2986,3684,Manning-Hamilton,Vision-oriented scalable definition,97300,153216,successful,2043,US,USD,1609221600,1622350800,False,True,food/food trucks,food,food trucks,cat1
996,2031,5784,Butler LLC,Future-proofed upward-trending migration,6600,4814,failed,112,US,USD,1634274000,1638252000,False,False,theater/plays,theater,plays,cat4
997,1627,1498,Ball LLC,Right-sized full-range throughput,7600,4603,canceled,139,IT,EUR,1636174800,1639116000,False,False,theater/plays,theater,plays,cat4
998,2175,6073,"Taylor, Santiago and Flores",Polarized composite customer loyalty,66600,37823,failed,374,US,USD,1602133200,1618117200,False,True,music/indie rock,music,indie rock,cat2
999,1788,4939,"Hernandez, Norton and Kelley",Expanded eco-centric policy,111100,62819,canceled,1122,US,USD,1609308000,1629262800,False,False,food/food trucks,food,food trucks,cat1

In [ ]:
# Export the DataFrame as a CSV file. LISA WILL DO THIS
campaign_cleaned.to_csv("Resources/campaign.csv", index=False)

### Extract the contacts.xlsx Data.

In [ ]:
# Read the data into a Pandas DataFrame. Use the `header=2` parameter when reading in the data. AMANUEL STARTS HERE
contact_info_df = pd.read_excel('Resources/contacts.xlsx', header=2)
contact_info_df.head()

### Create the Contacts DataFrame 
---
**Create a Contacts DataFrame that has the following columns:**
- A column named "contact_id"  that contains the unique number of the contact person.
- A column named "first_name" that contains the first name of the contact person.
- A column named "last_name" that contains the first name of the contact person.
- A column named "email" that contains the email address of the contact person

Then export the DataFrame as a `contacts.csv` CSV file.

### Option 1: Use Pandas to create the contacts DataFrame.

In [ ]:
# Iterate through the contact_info_df and convert each row to a dictionary.
import json
dict_values = []


# Print out the list of values for each row.
print(dict_values)

In [ ]:
# Create a contact_info DataFrame and add each list of values, i.e., each row 
# to the 'contact_id', 'name', 'email' columns.

In [ ]:
# Check the datatypes.

In [ ]:
# Create a "first"name" and "last_name" column with the first and last names from the "name" column. 


# Drop the contact_name column

In [ ]:
# Reorder the columns

In [ ]:
# Check the datatypes one more time before exporting as CSV file.

In [ ]:
# Export the DataFrame as a CSV file. 
contacts_df_clean.to_csv("Resources/contacts.csv", encoding='utf8', index=False)

### Option 2: Use regex to create the contacts DataFrame.

In [ ]:
contact_info_df_copy = contact_info_df.copy()
contact_info_df_copy.head()

In [ ]:
# Extract the four-digit contact ID number.

In [ ]:
# Check the datatypes.

In [ ]:
# Convert the "contact_id" column to an int64 data type.

In [ ]:
# Extract the name of the contact and add it to a new column.

In [ ]:
# Extract the email from the contacts and add the values to a new column.

In [ ]:
# Create a copy of the contact_info_df with the 'contact_id', 'name', 'email' columns.

In [ ]:
# Create a "first"name" and "last_name" column with the first and last names from the "name" column. 


# Drop the contact_name column

In [ ]:
# Reorder the columns

In [ ]:
# Check the datatypes one more time before exporting as CSV file.

In [ ]:
# Export the DataFrame as a CSV file. 
# contacts_df_clean.to_csv("Resources/contacts.csv", encoding='utf8', index=False)