In [1]:
# Import dependencies
import pandas as pd
import numpy as np
pd.set_option('max_colwidth', 400)

### Extract the crowdfunding.xlsx Data

In [6]:
# Read the data into a Pandas DataFrame
crowdfunding_data = pd.read_excel('Resources/crowdfunding.xlsx')
crowdfunding_data.head()

,cf_id,contact_id,company_name,blurb,goal,pledged,outcome,backers_count,country,currency,launched_at,deadline,staff_pick,spotlight,category & sub-category
0,147,4661,"Baldwin, Riley and Jackson",Pre-emptive tertiary standardization,100,0,failed,0,CA,CAD,1581573600,1614578400,False,False,food/food trucks
1,1621,3765,Odom Inc,Managed bottom-line architecture,1400,14560,successful,158,US,USD,1611554400,1621918800,False,True,music/rock
2,1812,4187,"Melton, Robinson and Fritz",Function-based leadingedge pricing structure,108400,142523,successful,1425,AU,AUD,1608184800,1640844000,False,False,technology/web
3,2156,4941,"Mcdonald, Gonzalez and Ross",Vision-oriented fresh-thinking conglomeration,4200,2477,failed,24,US,USD,1634792400,1642399200,False,False,music/rock
4,1365,2199,Larson-Little,Proactive foreground core,7600,5265,failed,53,US,USD,1608530400,1629694800,False,False,theater/plays

In [7]:
# Get a brief summary of the crowdfunding_info DataFrame.
print(crowdfunding)

     cf_id  contact_id                  company_name  \
0      147        4661    Baldwin, Riley and Jackson
1     1621        3765                      Odom Inc
2     1812        4187    Melton, Robinson and Fritz
3     2156        4941   Mcdonald, Gonzalez and Ross
4     1365        2199                 Larson-Little
..     ...         ...                           ...
995   2986        3684              Manning-Hamilton
996   2031        5784                    Butler LLC
997   1627        1498                      Ball LLC
998   2175        6073   Taylor, Santiago and Flores
999   1788        4939  Hernandez, Norton and Kelley

                                             blurb    goal  pledged  \
0             Pre-emptive tertiary standardization     100        0
1                 Managed bottom-line architecture    1400    14560
2     Function-based leadingedge pricing structure  108400   142523
3    Vision-oriented fresh-thinking conglomeration    4200     2477
4                        Proactive foreground core    7600     5265
..                                             ...     ...      ...
995            Vision-oriented scalable definition   97300   153216
996       Future-proofed upward-trending migration    6600     4814
997              Right-sized full-range throughput    7600     4603
998           Polarized composite customer loyalty   66600    37823
999                    Expanded eco-centric policy  111100    62819

        outcome  backers_count country currency  launched_at    deadline  \
0        failed              0      CA      CAD   1581573600  1614578400
1    successful            158      US      USD   1611554400  1621918800
2    successful           1425      AU      AUD   1608184800  1640844000
3        failed             24      US      USD   1634792400  1642399200
4        failed             53      US      USD   1608530400  1629694800
..          ...            ...     ...      ...          ...         ...
995  successful           2043      US      USD   1609221600  1622350800
996      failed            112      US      USD   1634274000  1638252000
997    canceled            139      IT      EUR   1636174800  1639116000
998      failed            374      US      USD   1602133200  1618117200
999    canceled           1122      US      USD   1609308000  1629262800

     staff_pick  spotlight category & sub-category
0         False      False        food/food trucks
1         False       True              music/rock
2         False      False          technology/web
3         False      False              music/rock
4         False      False           theater/plays
..          ...        ...                     ...
995       False       True        food/food trucks
996       False      False           theater/plays
997       False      False           theater/plays
998       False       True        music/indie rock
999       False      False        food/food trucks

[1000 rows x 15 columns]

### Create the Category and Subcategory DataFrames
---
**Create a Category DataFrame that has the following columns:**
- A "category_id" column that is numbered sequential form 1 to the length of the number of unique categories.
- A "category" column that has only the categories.

Export the DataFrame as a `category.csv` CSV file.

**Create a SubCategory DataFrame that has the following columns:**
- A "subcategory_id" column that is numbered sequential form 1 to the length of the number of unique subcategories.
- A "subcategory" column that has only the subcategories. 

Export the DataFrame as a `subcategory.csv` CSV file.

In [9]:

# Split the 'Category & Sub-Category' column into 'Category' and 'Sub-Category' columns
crowdfunding_data[['category', 'sub-category']] = crowdfunding_data['category & sub-category'].str.split('/', n=1, expand=True)

# Display the updated DataFrame
crowdfunding_data

# Get the crowdfunding_info_df columns.
#Find the unique categories in the 'category' column:
unique_categories = crowdfunding_data['category'].unique()

#Create a new DataFrame to store the mapping of category names to category IDs:
category_mapping = pd.DataFrame({'category': unique_categories})

#Add a new column 'category_id' to the category_mapping DataFrame with entries going sequentially from "cat1" to "catn":
category_mapping['category_id'] = 'cat' + (category_mapping.index + 1).astype(str)

#Merge the original DataFrame crowdfunding_data with the category_mapping DataFrame to add the 'category_id' column based on the 'category' column:
crowdfunding_data = crowdfunding_data.merge(category_mapping, on='category', how='left')

crowdfunding_data

,cf_id,contact_id,company_name,blurb,goal,pledged,outcome,backers_count,country,currency,launched_at,deadline,staff_pick,spotlight,category & sub-category,category,sub-category,category_id
0,147,4661,"Baldwin, Riley and Jackson",Pre-emptive tertiary standardization,100,0,failed,0,CA,CAD,1581573600,1614578400,False,False,food/food trucks,food,food trucks,cat1
1,1621,3765,Odom Inc,Managed bottom-line architecture,1400,14560,successful,158,US,USD,1611554400,1621918800,False,True,music/rock,music,rock,cat2
2,1812,4187,"Melton, Robinson and Fritz",Function-based leadingedge pricing structure,108400,142523,successful,1425,AU,AUD,1608184800,1640844000,False,False,technology/web,technology,web,cat3
3,2156,4941,"Mcdonald, Gonzalez and Ross",Vision-oriented fresh-thinking conglomeration,4200,2477,failed,24,US,USD,1634792400,1642399200,False,False,music/rock,music,rock,cat2
4,1365,2199,Larson-Little,Proactive foreground core,7600,5265,failed,53,US,USD,1608530400,1629694800,False,False,theater/plays,theater,plays,cat4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,2986,3684,Manning-Hamilton,Vision-oriented scalable definition,97300,153216,successful,2043,US,USD,1609221600,1622350800,False,True,food/food trucks,food,food trucks,cat1
996,2031,5784,Butler LLC,Future-proofed upward-trending migration,6600,4814,failed,112,US,USD,1634274000,1638252000,False,False,theater/plays,theater,plays,cat4
997,1627,1498,Ball LLC,Right-sized full-range throughput,7600,4603,canceled,139,IT,EUR,1636174800,1639116000,False,False,theater/plays,theater,plays,cat4
998,2175,6073,"Taylor, Santiago and Flores",Polarized composite customer loyalty,66600,37823,failed,374,US,USD,1602133200,1618117200,False,True,music/indie rock,music,indie rock,cat2
999,1788,4939,"Hernandez, Norton and Kelley",Expanded eco-centric policy,111100,62819,canceled,1122,US,USD,1609308000,1629262800,False,False,food/food trucks,food,food trucks,cat1

In [11]:
# Get the unique categories and subcategories in separate lists.
print(crowdfunding_data)

     cf_id  contact_id                  company_name  \
0      147        4661    Baldwin, Riley and Jackson
1     1621        3765                      Odom Inc
2     1812        4187    Melton, Robinson and Fritz
3     2156        4941   Mcdonald, Gonzalez and Ross
4     1365        2199                 Larson-Little
..     ...         ...                           ...
995   2986        3684              Manning-Hamilton
996   2031        5784                    Butler LLC
997   1627        1498                      Ball LLC
998   2175        6073   Taylor, Santiago and Flores
999   1788        4939  Hernandez, Norton and Kelley

                                             blurb    goal  pledged  \
0             Pre-emptive tertiary standardization     100        0
1                 Managed bottom-line architecture    1400    14560
2     Function-based leadingedge pricing structure  108400   142523
3    Vision-oriented fresh-thinking conglomeration    4200     2477
4                        Proactive foreground core    7600     5265
..                                             ...     ...      ...
995            Vision-oriented scalable definition   97300   153216
996       Future-proofed upward-trending migration    6600     4814
997              Right-sized full-range throughput    7600     4603
998           Polarized composite customer loyalty   66600    37823
999                    Expanded eco-centric policy  111100    62819

        outcome  backers_count country currency  launched_at    deadline  \
0        failed              0      CA      CAD   1581573600  1614578400
1    successful            158      US      USD   1611554400  1621918800
2    successful           1425      AU      AUD   1608184800  1640844000
3        failed             24      US      USD   1634792400  1642399200
4        failed             53      US      USD   1608530400  1629694800
..          ...            ...     ...      ...          ...         ...
995  successful           2043      US      USD   1609221600  1622350800
996      failed            112      US      USD   1634274000  1638252000
997    canceled            139      IT      EUR   1636174800  1639116000
998      failed            374      US      USD   1602133200  1618117200
999    canceled           1122      US      USD   1609308000  1629262800

     staff_pick  spotlight category & sub-category    category sub-category  \
0         False      False        food/food trucks        food  food trucks
1         False       True              music/rock       music         rock
2         False      False          technology/web  technology          web
3         False      False              music/rock       music         rock
4         False      False           theater/plays     theater        plays
..          ...        ...                     ...         ...          ...
995       False       True        food/food trucks        food  food trucks
996       False      False           theater/plays     theater        plays
997       False      False           theater/plays     theater        plays
998       False       True        music/indie rock       music   indie rock
999       False      False        food/food trucks        food  food trucks

    category_id
0          cat1
1          cat2
2          cat3
3          cat2
4          cat4
..          ...
995        cat1
996        cat4
997        cat4
998        cat2
999        cat1

[1000 rows x 18 columns]

In [14]:
# Get the number of distinct values in the categories and subcategories lists.
print(len(crowdfunding_data))

1000

In [ ]:
# Create a category DataFrame with the category_id array as the category_id and categories list as the category name.

# Create a category DataFrame with the subcategory_id array as the subcategory_id and subcategories list as the subcategory name.

In [15]:
crowdfunding_data

,cf_id,contact_id,company_name,blurb,goal,pledged,outcome,backers_count,country,currency,launched_at,deadline,staff_pick,spotlight,category & sub-category,category,sub-category,category_id
0,147,4661,"Baldwin, Riley and Jackson",Pre-emptive tertiary standardization,100,0,failed,0,CA,CAD,1581573600,1614578400,False,False,food/food trucks,food,food trucks,cat1
1,1621,3765,Odom Inc,Managed bottom-line architecture,1400,14560,successful,158,US,USD,1611554400,1621918800,False,True,music/rock,music,rock,cat2
2,1812,4187,"Melton, Robinson and Fritz",Function-based leadingedge pricing structure,108400,142523,successful,1425,AU,AUD,1608184800,1640844000,False,False,technology/web,technology,web,cat3
3,2156,4941,"Mcdonald, Gonzalez and Ross",Vision-oriented fresh-thinking conglomeration,4200,2477,failed,24,US,USD,1634792400,1642399200,False,False,music/rock,music,rock,cat2
4,1365,2199,Larson-Little,Proactive foreground core,7600,5265,failed,53,US,USD,1608530400,1629694800,False,False,theater/plays,theater,plays,cat4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,2986,3684,Manning-Hamilton,Vision-oriented scalable definition,97300,153216,successful,2043,US,USD,1609221600,1622350800,False,True,food/food trucks,food,food trucks,cat1
996,2031,5784,Butler LLC,Future-proofed upward-trending migration,6600,4814,failed,112,US,USD,1634274000,1638252000,False,False,theater/plays,theater,plays,cat4
997,1627,1498,Ball LLC,Right-sized full-range throughput,7600,4603,canceled,139,IT,EUR,1636174800,1639116000,False,False,theater/plays,theater,plays,cat4
998,2175,6073,"Taylor, Santiago and Flores",Polarized composite customer loyalty,66600,37823,failed,374,US,USD,1602133200,1618117200,False,True,music/indie rock,music,indie rock,cat2
999,1788,4939,"Hernandez, Norton and Kelley",Expanded eco-centric policy,111100,62819,canceled,1122,US,USD,1609308000,1629262800,False,False,food/food trucks,food,food trucks,cat1

In [17]:
# Export categories_df and subcategories_df as CSV files.
crowdfunding_data.to_csv("Resources/category.csv", index=False)

In [25]:
# Create a copy of the crowdfunding_info_df DataFrame name campaign_df. 
crowdfunding_data = crowdfunding_data.copy()
crowdfunding_data.head()

,cf_id,contact_id,company_name,blurb,goal,pledged,outcome,backers_count,country,currency,launched_at,deadline,staff_pick,spotlight,category & sub-category,category,sub-category,category_id
0,147,4661,"Baldwin, Riley and Jackson",Pre-emptive tertiary standardization,100,0,failed,0,CA,CAD,1581573600,1614578400,False,False,food/food trucks,food,food trucks,cat1
1,1621,3765,Odom Inc,Managed bottom-line architecture,1400,14560,successful,158,US,USD,1611554400,1621918800,False,True,music/rock,music,rock,cat2
2,1812,4187,"Melton, Robinson and Fritz",Function-based leadingedge pricing structure,108400,142523,successful,1425,AU,AUD,1608184800,1640844000,False,False,technology/web,technology,web,cat3
3,2156,4941,"Mcdonald, Gonzalez and Ross",Vision-oriented fresh-thinking conglomeration,4200,2477,failed,24,US,USD,1634792400,1642399200,False,False,music/rock,music,rock,cat2
4,1365,2199,Larson-Little,Proactive foreground core,7600,5265,failed,53,US,USD,1608530400,1629694800,False,False,theater/plays,theater,plays,cat4

In [23]:
# Format the launched_date and end_date columns to datetime format
from datetime import datetime as dt

In [24]:
# Merge the campaign_df with the category_df on the "category" column and 
# the subcategory_df on the "subcategory" column.


crowdfunding_data
crowdfunding_data.tail(10)

,cf_id,contact_id,company_name,blurb,goal,pledged,outcome,backers_count,country,currency,launched_at,deadline,staff_pick,spotlight,category & sub-category,category,sub-category,category_id
990,1561,5500,Ortiz-Roberts,Devolved foreground customer loyalty,7800,6839,failed,64,US,USD,1623214800,1623992400,False,True,film & video/drama,film & video,drama,cat5
991,2632,3494,Ramirez LLC,Reduced reciprocal focus group,9800,11091,successful,241,US,USD,1607493600,1622005200,False,True,music/rock,music,rock,cat2
992,439,3924,Morrow Inc,Networked global migration,3100,13223,successful,132,US,USD,1592110800,1612850400,False,True,film & video/drama,film & video,drama,cat5
993,461,3521,Erickson-Rogers,De-engineered even-keeled definition,9800,7608,canceled,75,IT,EUR,1625288400,1625720400,False,True,photography/photography books,photography,photography books,cat8
994,1419,5262,"Leach, Rich and Price",Implemented bi-directional flexibility,141100,74073,failed,842,US,USD,1636956000,1638856800,False,True,publishing/translations,publishing,translations,cat6
995,2986,3684,Manning-Hamilton,Vision-oriented scalable definition,97300,153216,successful,2043,US,USD,1609221600,1622350800,False,True,food/food trucks,food,food trucks,cat1
996,2031,5784,Butler LLC,Future-proofed upward-trending migration,6600,4814,failed,112,US,USD,1634274000,1638252000,False,False,theater/plays,theater,plays,cat4
997,1627,1498,Ball LLC,Right-sized full-range throughput,7600,4603,canceled,139,IT,EUR,1636174800,1639116000,False,False,theater/plays,theater,plays,cat4
998,2175,6073,"Taylor, Santiago and Flores",Polarized composite customer loyalty,66600,37823,failed,374,US,USD,1602133200,1618117200,False,True,music/indie rock,music,indie rock,cat2
999,1788,4939,"Hernandez, Norton and Kelley",Expanded eco-centric policy,111100,62819,canceled,1122,US,USD,1609308000,1629262800,False,False,food/food trucks,food,food trucks,cat1

In [ ]:
# Export the DataFrame as a CSV file. LISA WILL DO THIS
campaign_cleaned.to_csv("Resources/campaign.csv", index=False)

### Extract the contacts.xlsx Data.

In [ ]:
# Read the data into a Pandas DataFrame. Use the `header=2` parameter when reading in the data. AMANUEL STARTS HERE
contact_info_df = pd.read_excel('Resources/contacts.xlsx', header=2)
contact_info_df.head()

### Create the Contacts DataFrame 
---
**Create a Contacts DataFrame that has the following columns:**
- A column named "contact_id"  that contains the unique number of the contact person.
- A column named "first_name" that contains the first name of the contact person.
- A column named "last_name" that contains the first name of the contact person.
- A column named "email" that contains the email address of the contact person

Then export the DataFrame as a `contacts.csv` CSV file.

### Option 1: Use Pandas to create the contacts DataFrame.

In [ ]:
# Iterate through the contact_info_df and convert each row to a dictionary.
import json
dict_values = []


# Print out the list of values for each row.
print(dict_values)

In [ ]:
# Create a contact_info DataFrame and add each list of values, i.e., each row 
# to the 'contact_id', 'name', 'email' columns.

In [ ]:
# Check the datatypes.

In [ ]:
# Create a "first"name" and "last_name" column with the first and last names from the "name" column. 


# Drop the contact_name column

In [ ]:
# Reorder the columns

In [ ]:
# Check the datatypes one more time before exporting as CSV file.

In [ ]:
# Export the DataFrame as a CSV file. 
contacts_df_clean.to_csv("Resources/contacts.csv", encoding='utf8', index=False)

### Option 2: Use regex to create the contacts DataFrame.

In [ ]:
contact_info_df_copy = contact_info_df.copy()
contact_info_df_copy.head()

In [ ]:
# Extract the four-digit contact ID number.

In [ ]:
# Check the datatypes.

In [ ]:
# Convert the "contact_id" column to an int64 data type.

In [ ]:
# Extract the name of the contact and add it to a new column.

In [ ]:
# Extract the email from the contacts and add the values to a new column.

In [ ]:
# Create a copy of the contact_info_df with the 'contact_id', 'name', 'email' columns.

In [ ]:
# Create a "first"name" and "last_name" column with the first and last names from the "name" column. 


# Drop the contact_name column

In [ ]:
# Reorder the columns

In [ ]:
# Check the datatypes one more time before exporting as CSV file.

In [ ]:
# Export the DataFrame as a CSV file. 
# contacts_df_clean.to_csv("Resources/contacts.csv", encoding='utf8', index=False)