In [14]:
#df sub-category.csv project 2

import pandas as pd

crowdfunding_data = pd.read_csv(r'C:\Users\soone\Crowdfunding_ETL\crowdfunding_data.csv')

#Display the first few rows of the df
print(crowdfunding_data.head())

   cf_id  contact_id                 company_name  \
0    147        4661   Baldwin, Riley and Jackson
1   1621        3765                     Odom Inc
2   1812        4187   Melton, Robinson and Fritz
3   2156        4941  Mcdonald, Gonzalez and Ross
4   1365        2199                Larson-Little

                                           blurb    goal  pledged     outcome  \
0           Pre-emptive tertiary standardization     100        0      failed
1               Managed bottom-line architecture    1400    14560  successful
2   Function-based leadingedge pricing structure  108400   142523  successful
3  Vision-oriented fresh-thinking conglomeration    4200     2477      failed
4                      Proactive foreground core    7600     5265      failed

   backers_count country currency  launched_at    deadline  staff_pick  \
0              0      CA      CAD   1581573600  1614578400       False
1            158      US      USD   1611554400  1621918800       False
2           1425      AU      AUD   1608184800  1640844000       False
3             24      US      USD   1634792400  1642399200       False
4             53      US      USD   1608530400  1629694800       False

   spotlight category & sub-category    category sub-category category_id
0      False        food/food trucks        food  food trucks        cat1
1       True              music/rock       music         rock        cat2
2      False          technology/web  technology          web        cat3
3      False              music/rock       music         rock        cat2
4      False           theater/plays     theater        plays        cat4

In [38]:
#Find the unique categories in the 'sub-category' column:
unique_subcategories = crowdfunding_data['sub-category'].unique()

#Create a new DataFrame to store the mapping of sub-category names to sub-category IDs:
subcategory_mapping = pd.DataFrame({'sub-category': unique_subcategories})

#Add a new column 'sub-category_id' to the sub-category_mapping DataFrame with entries going sequentially from "cat1" to "catn":
subcategory_mapping['sub-category_id'] = 'subcat' + (subcategory_mapping.index + 1).astype(str)

#Merge the original DataFrame crowdfunding_data with the category_mapping DataFrame to add the 'sub-category_id' column based on the 'sub-category' column:
subcategory = crowdfunding_data.merge(subcategory_mapping, on='sub-category', how='left')

subcategory

,cf_id,contact_id,company_name,blurb,goal,pledged,outcome,backers_count,country,currency,launched_at,deadline,staff_pick,spotlight,category & sub-category,category,sub-category,category_id,sub-category_id_x,sub-category_id_y
0,147,4661,"Baldwin, Riley and Jackson",Pre-emptive tertiary standardization,100,0,failed,0,CA,CAD,1581573600,1614578400,False,False,food/food trucks,food,food trucks,cat1,subcat1,subcat1
1,1621,3765,Odom Inc,Managed bottom-line architecture,1400,14560,successful,158,US,USD,1611554400,1621918800,False,True,music/rock,music,rock,cat2,subcat2,subcat2
2,1812,4187,"Melton, Robinson and Fritz",Function-based leadingedge pricing structure,108400,142523,successful,1425,AU,AUD,1608184800,1640844000,False,False,technology/web,technology,web,cat3,subcat3,subcat3
3,2156,4941,"Mcdonald, Gonzalez and Ross",Vision-oriented fresh-thinking conglomeration,4200,2477,failed,24,US,USD,1634792400,1642399200,False,False,music/rock,music,rock,cat2,subcat2,subcat2
4,1365,2199,Larson-Little,Proactive foreground core,7600,5265,failed,53,US,USD,1608530400,1629694800,False,False,theater/plays,theater,plays,cat4,subcat4,subcat4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,2986,3684,Manning-Hamilton,Vision-oriented scalable definition,97300,153216,successful,2043,US,USD,1609221600,1622350800,False,True,food/food trucks,food,food trucks,cat1,subcat1,subcat1
996,2031,5784,Butler LLC,Future-proofed upward-trending migration,6600,4814,failed,112,US,USD,1634274000,1638252000,False,False,theater/plays,theater,plays,cat4,subcat4,subcat4
997,1627,1498,Ball LLC,Right-sized full-range throughput,7600,4603,canceled,139,IT,EUR,1636174800,1639116000,False,False,theater/plays,theater,plays,cat4,subcat4,subcat4
998,2175,6073,"Taylor, Santiago and Flores",Polarized composite customer loyalty,66600,37823,failed,374,US,USD,1602133200,1618117200,False,True,music/indie rock,music,indie rock,cat2,subcat8,subcat8
999,1788,4939,"Hernandez, Norton and Kelley",Expanded eco-centric policy,111100,62819,canceled,1122,US,USD,1609308000,1629262800,False,False,food/food trucks,food,food trucks,cat1,subcat1,subcat1

In [64]:
import pandas as pd

# Read the file with ISO-8859-1 encoding
subcategory = pd.read_csv('subcategory.csv', encoding='windows-1252')

print(subcategory.tail())



subcategory

     cf_id  contact_id                  company_name  \
995   2986        3684              Manning-Hamilton
996   2031        5784                    Butler LLC
997   1627        1498                      Ball LLC
998   2175        6073   Taylor, Santiago and Flores
999   1788        4939  Hernandez, Norton and Kelley

                                        blurb    goal  pledged     outcome  \
995       Vision-oriented scalable definition   97300   153216  successful
996  Future-proofed upward-trending migration    6600     4814      failed
997         Right-sized full-range throughput    7600     4603    canceled
998      Polarized composite customer loyalty   66600    37823      failed
999               Expanded eco-centric policy  111100    62819    canceled

     backers_count country currency  launched_at    deadline  staff_pick  \
995           2043      US      USD   1609221600  1622350800       False
996            112      US      USD   1634274000  1638252000       False
997            139      IT      EUR   1636174800  1639116000       False
998            374      US      USD   1602133200  1618117200       False
999           1122      US      USD   1609308000  1629262800       False

     spotlight category & sub-category category sub-category category_id  \
995       True        food/food trucks     food  food trucks        cat1
996      False           theater/plays  theater        plays        cat4
997      False           theater/plays  theater        plays        cat4
998       True        music/indie rock    music   indie rock        cat2
999      False        food/food trucks     food  food trucks        cat1

    sub-category_id
995         subcat1
996         subcat4
997         subcat4
998         subcat8
999         subcat1

,cf_id,contact_id,company_name,blurb,goal,pledged,outcome,backers_count,country,currency,launched_at,deadline,staff_pick,spotlight,category & sub-category,category,sub-category,category_id,sub-category_id
0,147,4661,"Baldwin, Riley and Jackson",Pre-emptive tertiary standardization,100,0,failed,0,CA,CAD,1581573600,1614578400,False,False,food/food trucks,food,food trucks,cat1,subcat1
1,1621,3765,Odom Inc,Managed bottom-line architecture,1400,14560,successful,158,US,USD,1611554400,1621918800,False,True,music/rock,music,rock,cat2,subcat2
2,1812,4187,"Melton, Robinson and Fritz",Function-based leadingedge pricing structure,108400,142523,successful,1425,AU,AUD,1608184800,1640844000,False,False,technology/web,technology,web,cat3,subcat3
3,2156,4941,"Mcdonald, Gonzalez and Ross",Vision-oriented fresh-thinking conglomeration,4200,2477,failed,24,US,USD,1634792400,1642399200,False,False,music/rock,music,rock,cat2,subcat2
4,1365,2199,Larson-Little,Proactive foreground core,7600,5265,failed,53,US,USD,1608530400,1629694800,False,False,theater/plays,theater,plays,cat4,subcat4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,2986,3684,Manning-Hamilton,Vision-oriented scalable definition,97300,153216,successful,2043,US,USD,1609221600,1622350800,False,True,food/food trucks,food,food trucks,cat1,subcat1
996,2031,5784,Butler LLC,Future-proofed upward-trending migration,6600,4814,failed,112,US,USD,1634274000,1638252000,False,False,theater/plays,theater,plays,cat4,subcat4
997,1627,1498,Ball LLC,Right-sized full-range throughput,7600,4603,canceled,139,IT,EUR,1636174800,1639116000,False,False,theater/plays,theater,plays,cat4,subcat4
998,2175,6073,"Taylor, Santiago and Flores",Polarized composite customer loyalty,66600,37823,failed,374,US,USD,1602133200,1618117200,False,True,music/indie rock,music,indie rock,cat2,subcat8
999,1788,4939,"Hernandez, Norton and Kelley",Expanded eco-centric policy,111100,62819,canceled,1122,US,USD,1609308000,1629262800,False,False,food/food trucks,food,food trucks,cat1,subcat1

In [67]:
# Selecting only two columns from the 'subcategory' DataFrame
subcategory_df = subcategory[['sub-category_id', 'sub-category']]

# Display the new DataFrame
print(subcategory_df.head())

subcategory_df

  sub-category_id sub-category
0         subcat1  food trucks
1         subcat2         rock
2         subcat3          web
3         subcat2         rock
4         subcat4        plays

    sub-category_id sub-category
0           subcat1  food trucks
1           subcat2         rock
2           subcat3          web
3           subcat2         rock
4           subcat4        plays
..              ...          ...
995         subcat1  food trucks
996         subcat4        plays
997         subcat4        plays
998         subcat8   indie rock
999         subcat1  food trucks

[1000 rows x 2 columns]

In [70]:
# Export the DataFrame as a CSV file
subcategory_df.to_csv('subcategory.csv', index=False)

In [48]:
print(subcategory.columns)

Index(['cf_id', 'contact_id', 'company_name', 'blurb', 'goal', 'pledged',
       'outcome', 'backers_count', 'country', 'currency', 'launched_at',
       'deadline', 'staff_pick', 'spotlight', 'category & sub-category',
       'category', 'sub-category', 'category_id', 'sub-category_id'],
      dtype='object')

In [68]:
# Select the two columns you want to keep
#selected_columns = ['sub-category_id', 'sub-category']

# Create a new DataFrame with only the selected columns
#subcategory_df = (selected_columns)

#print(selected_columns)
#results will be: ['sub-category_id', 'sub-category']